[linters]
disable-all = true
enable = ["gofmt", "goimports", "govet", "unused", "errcheck"]

[issues]
exclude-use-default = true
exclude-dirs = ["vendor", "runtime/sandcastle"]

[run]
timeout = "10m"
