version: "2"
linters:
  enable:
    - govet
    - revive
    - staticcheck
    - ineffassign
    - unused
    - misspell
formatters:
  enable:
    - goimports
issues:
  exclude-dirs-use-default: false
  exclude-files-use-default: false
