version: "2"

linters:
  default: none
  enable:
    - govet
    - unused
    - errcheck
  exclusions:
    paths:
      - vendor
      - runtime/sandcastle
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - vendor
      - runtime/sandcastle
