run:
  timeout: 10m
  
linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - unused
    - errcheck

issues:
  exclude-use-default: true
  exclude-dirs:
    - vendor
    - runtime/sandcastle
    - .git
    - dist/
    - node_modules
  exclude-rules:
    - path: 'runtime/sandcastle/src/.*\.ts'
      linters:
        - gofmt
        - goimports
        - govet
        - unused
        - errcheck
